# Generated by Django 4.0 on 2022-01-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCoder', '0002_alumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fecha_inscripcion',
            field=models.DateField(verbose_name='fecha'),
        ),
    ]
