# Generated by Django 4.0 on 2022-01-13 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCoder', '0003_alter_alumno_fecha_inscripcion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumno',
            new_name='Estudiante',
        ),
    ]
