# Generated by Django 4.0 on 2022-01-13 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCoder', '0004_rename_alumno_estudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='fecha_inscripcion',
        ),
    ]
