# Generated by Django 4.0 on 2022-01-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCoder', '0005_remove_estudiante_fecha_inscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='apellido')),
                ('email', models.EmailField(default='0000000', max_length=254, verbose_name='email')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(default='nada', max_length=254, verbose_name='email'),
            preserve_default=False,
        ),
    ]
